//Creating the Class 
//Date 02-03-2021
public class APEXAssignment {
    //initialize the Variables
    Private Integer VarSubResult;
    Private Double VarDivResult;
    //Function for Substraction
Public Integer MakeSubstraction(Integer a, Integer b)   
 {
     VarSubResult = a-b;
     Return VarSubResult;
 }
    //Function for Division
    Public Double MakeDivision(Integer a, Integer b)
    {
        VarDivResult = a/b;
        Return VarDivResult;
    }
}