public class CalculatorAPEXclass {
//Declaring the Variables
Private Static Integer Result;
    //Creating the SUM Function 
   Public static Integer Sum(integer a, Integer b){
        Result = a+b;
        Return Result;
    }
    //Creating Multiplication Function 
    Public static Void Product(Integer a,Integer b){
    Result = a*b;   
    System.debug('The Multiplication Result is '+Result);
    }

}